### ISSUE TITLE
$http(...).success has been removed from angular 1.6

### ISSUE THREAD

**Issue by adskjohn** [linnovate/meanio-users#6]
the MeanUser angular service in meanUser.js uses $http(...).success instead of the promise form and was deprecated, and finally removed in angular 1.6.0.  Currently linnovate/mean's bower.json uses latest of angular so this will cause new installs to start breaking.

**Comment by timelf123** [comment]
This is also used in meanio-admin afaik (was looking at this yday)

**Comment by quentinhayot** [comment]
Fixed in #7 (partly) and #8 (fully).

**Comment by timelf123** [comment]
Great work @quentinhayot thanks
